name: Unit Tests

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches: [master]
    paths-ignore:
    - '**.md'

jobs:
  test-js:
    name: JavaScript

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [ '12', '14' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Install NPM dependencies and build
      run: npm install

    - name: Run tests
      run: npm run test
