name: Unit Tests

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches: [master]
    paths-ignore:
    - '**.md'

jobs:
  test:
    name: JavaScript

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Npm install and build
      run: |
        npm ci

    - name: Running the tests
      run: npm run test
